// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChRLhXaefqw4tHBl51ObupwlPIgtDEDYw',
    appId: '1:963195966083:web:8f5d08934fb836d408c1b6',
    messagingSenderId: '963195966083',
    projectId: 'chatapp-b3b05',
    authDomain: 'chatapp-b3b05.firebaseapp.com',
    storageBucket: 'chatapp-b3b05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkhNM1x_E_xNEnsdKQxjSt-f4u183yLV8',
    appId: '1:963195966083:android:fb366543c670b4aa08c1b6',
    messagingSenderId: '963195966083',
    projectId: 'chatapp-b3b05',
    storageBucket: 'chatapp-b3b05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbRsj-kqFW-Y2qqVCCqTBjvWSkfZ9J2Kc',
    appId: '1:963195966083:ios:6cbcd639438eea5c08c1b6',
    messagingSenderId: '963195966083',
    projectId: 'chatapp-b3b05',
    storageBucket: 'chatapp-b3b05.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbRsj-kqFW-Y2qqVCCqTBjvWSkfZ9J2Kc',
    appId: '1:963195966083:ios:6cbcd639438eea5c08c1b6',
    messagingSenderId: '963195966083',
    projectId: 'chatapp-b3b05',
    storageBucket: 'chatapp-b3b05.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChRLhXaefqw4tHBl51ObupwlPIgtDEDYw',
    appId: '1:963195966083:web:4b544b075b4ee6ec08c1b6',
    messagingSenderId: '963195966083',
    projectId: 'chatapp-b3b05',
    authDomain: 'chatapp-b3b05.firebaseapp.com',
    storageBucket: 'chatapp-b3b05.firebasestorage.app',
  );
}
